title: Siuxoes - My personal code
description: Spanish|English blog about code

url: Siuxoes - My personal code
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Contact
   url: /contact.html

social:
   github: siuxoes
   email: sebastianleonteandroid@gmail.com
